default:
	clear;
	javac *.java;
clean:
	rm -f *.class;
	rm -f testText.txt
	rm -f testText*
turnin:
	zip jdt2725_et7226_program4.zip *
love:
	java Encoder frequenciesFile 1000
test1:
	java Encoder test1.txt 1000
test2:
	java Encoder test2.txt 1000
test3:
	java Encoder test3.txt 1000
test4:
	java Encoder test4.txt 1000