default:
	clear;
	javac *.java
clean:
	rm -f *.class
turnin:
	zip jdt2725_et7226_program5.zip *
love:
	java PasswordCrack dictionary pass1
babies:
	java PasswordCrack dictionary pass2
all: love babies