default:
	clear;
	javac *.java;
clean:
	rm -f *.class;
	rm -f *.enc*
turnin:
	zip jdt2725_et7226_program5.zip *
love:
	java AES e keyFile inputFile
babies:
	java AES d keyFile inputFile.enc
	cat inputFile.enc.dec