default:
	javac *.java;
clean:
	rm -f *.class;
	rm -f *.enc*
turnin:
	zip jdt2725_et7226_program5.zip *
love:
	java AES e README.txt < keyFile
babies:
	java AES d README.txt < keyFile
test: love babies